# Generated by Django 4.2.4 on 2023-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
